### ISSUE TITLE
Not working (old packages?)

### ISSUE THREAD

**Issue by IdanLevi** [chinalaunchlabs/xamarin-fb#1]
I can't get it working. Can you please upload a new example with the latest Xamarin.Forms packages/Update this one?

**Comment by TheIncredibleIllmo** [comment]
can you update your version and also could you explain the part where you declare IAccessToken and iOSToken because they are missed!

**Comment by chinalaunchlabs** [comment]
@TheIncredibleIllmo  I actually removed the IAccessToken and their native implementations because I realized they weren't necessary. The access token is handled by the FbAccessToken class now. The Android project should have worked, it was the iOS project I had forgotten to test. 

Anyway, I've updated the repo. Let me know if you still encounter problems.
